name: Check JSON syntax

on:
  push:
    branches:
      - master
    paths:
      - "**.json"
  pull_request:
    paths:
      - "**.json"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check all JSON syntax
        uses: limitusus/json-syntax-check@v1.0.3
        with:
          pattern: "\\.json$"
