name: tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  ci:
    strategy:
      matrix:
        # TODO support more versions
        python-version: ["3.12", "3.11", "3.10", "3.9", "3.8"]
        poetry-version: ["1.8.1"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run pytest
        run: poetry run pytest --cache-clear --cov --benchmark-json output.json

      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'pytest'
          output-file-path: output.json
          external-data-json-path: ./cache/output.json
          # Workflow will fail when an alert happens
          fail-on-alert: true
          #|
            #set -o pipefail
            # | tee pytest-coverage.txt
      # TODO figure out best way to display coverage
      #- name: Comment coverage
      #  uses: coroo/pytest-coverage-commentator@v1.0.2
